services:

    #
    # Object Managers
    #
    qbh.object_manager.product_tag:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %qbh.store.product.entity.product_tag.class%