services:

    #
    # Repositories
    #

    #
    # Repository for entity product
    #
    qbh.repository.product_tag:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %qbh.store.product.entity.product_tag.class%