Elcodi\Component\User\Entity\Abstracts\AbstractUser:
    type: mappedSuperclass
    fields:
        gender:
            column: gender
            type: integer
            nullable: true
        username:
            column: username
            type: string
            length: 255
            nullable: true
        password:
            column: password
            type: string
            length: 255
            nullable: true
        email:
            column: email
            type: string
            length: 255
            nullable: true
        firstname:
            column: firstname
            type: string
            length: 255
            nullable: true
        lastname:
            column: lastname
            type: string
            length: 255
            nullable: true
        birthday:
            column: birthday
            type: date
            nullable: true
        recoveryHash:
            column: recovery_hash
            type: string
            length: 255
            unique: true
            nullable: true

        # datetime
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        # enable
        enabled:
            column: enabled
            type: boolean

    lifecycleCallbacks:
            preUpdate: [loadUpdateAt]
            prePersist: [loadUpdateAt]
