knp_gaufrette:
    adapters:
        local:
            local:
                directory: %kernel.root_dir%/../web/images
                create: true
    filesystems:
        local:
            adapter:    local
