homepage:
    path: /
    defaults:
        _controller: StoreBundle:Frontend:index
        _locale: es

store_homepage:
    locales:
        es: "/es"
        en: "/en"
    defaults:
        _controller: StoreBundle:Frontend:index