#
# Store namespace
#
store_name:
    key: name
    namespace: store
    name: Store name
    type: string
    value: "Bamboo: Powered by Elcodi"

#
# Product namespace
#
product_use_stock:
    key: use_stock
    namespace: product
    name: Use Stock
    type: boolean
    value: true
