QBH\StoreBundle\Entity\Abstracts\AbstractTag:
    type: mappedSuperclass
    fields:
        name:
            column: username
            type: string
            length: 255
        # datetime
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        # enable
        enabled:
            column: enabled
            type: boolean

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]