services:

    #
    # Repositories
    #

    #
    # Repository for entity configuration
    #
    qbh.repository.configuration:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: QBH\StoreConfigurationBundle\Entity\Configuration
